image: buildpack-deps:stretch

release:
  only:
    - release@getto-systems-labo/dockerfiles-base
  script:
    - ./bin/push_tags.sh

update:
  only:
    - schedules
  script:
    - ./bin/update_release_version.sh
    - ./bin/push_tags.sh
