source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'rake', '~> 12.3.1'

gem 'exception_notification', '~> 4.2.2'
gem 'slack-notifier', '~> 2.3.2'

gem 'roda', '~> 3.13.0'

gem 'bcrypt', '~> 3.1.12'
gem 'authy', '~> 2.7.4'

gem 'sequel', '~> 5.13.0'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'

gem 'puma', '~> 3.12'

gem 'getto-initialize_with', '>= 1.0.0'
gem 'getto-roda', '>= 1.1.0'
gem 'getto-params', '>= 1.0.0'
gem 'getto-repository-sequel', '>= 1.0.0'

gem 'monban-core', '>= 1.1.0'
gem 'monban-repository', '>= 1.1.0'

group :development, :test do
  gem 'pry'
  gem 'minitest'
  gem 'simplecov', require: false
end
